# municipality code lookup - http://munstats.pa.gov/Public/FindLocalTax.aspx
# other municipality info - https://munstats.pa.gov/Public/FindMunicipality.aspx
# find longitude/latitude - https://support.google.com/maps/answer/18539

# note sure how to complete foundation, floor(frame) etc. fields (percent?)

# empty seed array
ind_0 = {"county" => "",
         "municipality_name" => "",
         "name" => "",
         "street_address" => "",
         "city" => "",
         "zip_code" => "",
         "municipality_code" => "",
         "date_damaged" => "",
         "longitude" => "",
         "latitude" => "",
         "location_notes" => "",
         "primary_home" => "",
         "renter" => "",
         "foundation_home" => "",
         "floor_frame_home" => "",
         "exterior_walls_home" => "",
         "roof_home" => "",
         "interior_walls_home" => "",
         "plumbing_home" => "",
         "heating_ac_home" => "",
         "electrical_home" => "",
         "floor_frame_mobile" => "",
         "exterior_walls_mobile" => "",
         "roof_mobile" => "",
         "interior_walls_mobile" => "",
         "destroyed_home" => "",
         "major_home" => "",
         "minor_home" => "",
         "affected_home" => "",
         "inaccessible_home" => "",
         "destroyed_mobile" => "",
         "major_mobile" => "",
         "minor_mobile" => "",
         "affected_mobile" => "",
         "inaccessible_mobile" => "",
         "comments" => "",
         "flood_insurance" => "",
         "basement_water" => "",
         "first_floor_water" => "",
         "height_water" => "",
         "add_comments" => "",
         "assessor_name" => "",
         "date_assessed" => ""}

# example seed array with some very minimal values
ind_1 = {"county" => "Allegheny",
         # "municipality_name" => "",
         # "name" => "",
         # "street_address" => "",
         # "city" => "",
         # "zip_code" => "",
         # "municipality_code" => "",
         # "date_damaged" => "",
         # "longitude" => "",
         # "latitude" => "",
         # "location_notes" => "",
         # "primary_home" => "",
         # "renter" => "",
         # "foundation_home" => "",
         # "floor_frame_home" => "",
         # "exterior_walls_home" => "",
         # "roof_home" => "",
         # "interior_walls_home" => "",
         # "plumbing_home" => "",
         # "heating_ac_home" => "",
         # "electrical_home" => "",
         # "floor_frame_mobile" => "",
         # "exterior_walls_mobile" => "",
         # "roof_mobile" => "",
         # "interior_walls_mobile" => "",
         # "destroyed_home" => "",
         # "major_home" => "",
         # "minor_home" => "",
         # "affected_home" => "",
         # "inaccessible_home" => "",
         # "destroyed_mobile" => "",
         # "major_mobile" => "",
         # "minor_mobile" => "",
         # "affected_mobile" => "",
         # "inaccessible_mobile" => "",
         # "comments" => "",
         # "flood_insurance" => "",
         # "basement_water" => "",
         # "first_floor_water" => "",
         # "height_water" => "",
         # "add_comments" => "",
         # "assessor_name" => "",
         "date_assessed" => "04/04/2016"}

# example seed array with some initial values
ind_2 = {"county" => "Allegheny",
         "municipality_name" => "Ohara Township",
         "name" => "John Doe",
         "street_address" => "123 Main Street",
         "city" => "Pittsburgh",
         "zip_code" => "15215",
         "municipality_code" => "700102",
         "date_damaged" => "01/26/2017",
         "longitude" => "40.502422",
         "latitude" => "-79.919777",
         # "location_notes" => "",
         "primary_home" => "yes",
         "renter" => "no",
         # "foundation_home" => "",
         # "floor_frame_home" => "",
         # "exterior_walls_home" => "",
         # "roof_home" => "",
         # "interior_walls_home" => "",
         # "plumbing_home" => "",
         # "heating_ac_home" => "",
         # "electrical_home" => "",
         # "floor_frame_mobile" => "",
         # "exterior_walls_mobile" => "",
         # "roof_mobile" => "",
         # "interior_walls_mobile" => "",
         # "destroyed_home" => "",
         # "major_home" => "",
         # "minor_home" => "",
         # "affected_home" => "",
         # "inaccessible_home" => "",
         # "destroyed_mobile" => "",
         # "major_mobile" => "",
         # "minor_mobile" => "",
         # "affected_mobile" => "",
         # "inaccessible_mobile" => "",
         "comments" => "Initial contact established, will assess on 4/18/2017.",
         # "flood_insurance" => "",
         # "basement_water" => "",
         # "first_floor_water" => "",
         # "height_water" => "",
         # "add_comments" => "",
         # "assessor_name" => "",
         "date_assessed" => "02/01/2016"}